[book]
authors = ["Ken Martin", "Bill Hoffman"]
language = "en"
text-direction = "ltr"
multilingual = false
src = "src"
title = "Mastering CMake"

[output.html]
site-url = "/mastering-cmake/"
git-repository-url = "https://github.com/jbonadiman/mastering-cmake"
git-repository-icon = "fa-github"

[output.html.print]
page-break = false

[output.html.fold]
enable = true
